#!/bin/bash

git_version_check() {
    repo="$1"

    release=$(
        curl --silent -m 10 --connect-timeout 5 "https://api.github.com/repos/$repo/releases/latest"
    )

    tag=$(echo "$release" | grep -oP '"tag_name": "\K[^"]+')

    echo $tag
}

update_versions() {
    #plugin versions
    hiltDagger=$(git_version_check google/dagger | sed 's/^dagger-//')
    kspVersion=$(git_version_check google/ksp)

    #show plugin versons
    echo "Dagger version is $hiltDagger"
    echo "KSP version is $kspVersion"
}
